### ISSUE TITLE
Dionaeaが起動しないのですが．．．

### ISSUE THREAD

**Issue by k838450** [kobad/dionaea-docker#1]
/opt/dionaea/bin/dionaea -D
を実行したのですが
Dionaea Version 0.1.0
Compiled on Linux/x86_64 at Oct 10 2017 08:08:01 with gcc 5.4.0 20160609
Started on 7c97751ad691 running Linux/x86_64 release 3.10.0-327.36.3.el7.x86_64

Trace/breakpoint trap (core dumped)
で落ちてしまいます．

nmap localhostをしたら確かに記載されている通りの返答をするのですがDionaea自体は起動していません．
このDockerfileはハニーポットとしての使用は想定していないのでしょうか？

**Comment by kobadlve** [comment]
ご指摘ありがとうございます。どうやら`config/setup.sh`が間違っているようでとりあえずコメントアウトしました。core dumpの問題は解決できたと思います.
```
# Setup Dionaea
#ADD config /opt/dionaea/etc/dionaea/config
#RUN /bin/bash /opt/dionaea/etc/dionaea/config/setup.sh
```
